-- Create account table
CREATE TABLE ACCOUNT (
    USERNAME VARCHAR(30) NOT NULL PRIMARY KEY,
    PASSWORD VARCHAR(100),
    FIRST_NAME VARCHAR(20),
    LAST_NAME VARCHAR(20),
    FULL_NAME VARCHAR(50),
    IMAGE VARCHAR(100),
    EMAIL VARCHAR(100) NOT NULL,
    PHONE VARCHAR(11),
    ADDRESS TEXT,
    ROLE INT
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- Create shop table
CREATE TABLE SHOP (
    SHOP_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    SHOP_NAME VARCHAR(50),
    LAT VARCHAR(100),
    LNG VARCHAR(100),
    DATE_CREATED DATETIME,
    PHONE VARCHAR(11),
    TIME_OPEN VARCHAR(10),
    TIME_CLOSE VARCHAR(10),
    STATUS INT,
    DISCOUNT DOUBLE,
    ADDRESS TEXT,
    DETAIL TEXT,
    VIEW VARCHAR(100),
    USERNAME VARCHAR(100)
)ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- Create save table
CREATE TABLE SAVE (
    SAVE_ID INT,
    USERNAME VARCHAR(30),
    SHOP_ID INT
)ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- Create comment table
CREATE TABLE COMMENT (
    COMMENT_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(30),
    SHOP_ID INT,
    CONTENT TEXT,
    DATE_CREATED DATETIME
)ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- Create rate table
CREATE TABLE RATE (
    RATE_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    SHOP_ID INT,
    USERNAME VARCHAR(30),
    SCORE INT
)ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- Create type table
CREATE TABLE TYPE (
    TYPE_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TYPE_NAME VARCHAR(50)
)ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- Create foods table
CREATE TABLE FOODS (
    FOOD_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    SHOP_ID INT,
    FOOD_NAME VARCHAR(50)
)ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- Create type_shop table
CREATE TABLE TYPE_SHOP (
    TYPE_ID INT,
    SHOP_ID INT
)ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- Create feedback table
CREATE TABLE FEEDBACK (
    FEEDBACK_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CONTENT TEXT,
    USERNAME VARCHAR(30)
)ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;;

